naming:
  FunctionNaming:
    active: false
  MatchingDeclarationName:
    active: false

complexity:
  TooManyFunctions:
    active: false

style:
  DestructuringDeclarationWithTooManyEntries:
    active: false
  NewLineAtEndOfFile:
    active: false

exceptions:
  TooGenericExceptionCaught:
    active: false